################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/scott/repos/code/openstm/batteryCharger/Src/arm_common_tables.c \
C:/Users/scott/repos/code/openstm/batteryCharger/Src/arm_cos_f32.c \
C:/Users/scott/repos/code/openstm/batteryCharger/Src/arm_sin_f32.c \
C:/Users/scott/repos/code/openstm/batteryCharger/Src/battery-socket.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/ethernetif.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/freertos.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/lwip.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/main.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/stm32f4xx_hal_msp.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/stm32f4xx_it.c 

OBJS += \
./Application/User/arm_common_tables.o \
./Application/User/arm_cos_f32.o \
./Application/User/arm_sin_f32.o \
./Application/User/battery-socket.o \
./Application/User/ethernetif.o \
./Application/User/freertos.o \
./Application/User/lwip.o \
./Application/User/main.o \
./Application/User/stm32f4xx_hal_msp.o \
./Application/User/stm32f4xx_it.o 

C_DEPS += \
./Application/User/arm_common_tables.d \
./Application/User/arm_cos_f32.d \
./Application/User/arm_sin_f32.d \
./Application/User/battery-socket.d \
./Application/User/ethernetif.d \
./Application/User/freertos.d \
./Application/User/lwip.d \
./Application/User/main.d \
./Application/User/stm32f4xx_hal_msp.d \
./Application/User/stm32f4xx_it.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/arm_common_tables.o: C:/Users/scott/repos/code/openstm/batteryCharger/Src/arm_common_tables.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/arm_common_tables.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/arm_cos_f32.o: C:/Users/scott/repos/code/openstm/batteryCharger/Src/arm_cos_f32.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/arm_cos_f32.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/arm_sin_f32.o: C:/Users/scott/repos/code/openstm/batteryCharger/Src/arm_sin_f32.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/arm_sin_f32.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/battery-socket.o: C:/Users/scott/repos/code/openstm/batteryCharger/Src/battery-socket.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/battery-socket.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/ethernetif.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/ethernetif.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/ethernetif.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/freertos.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/freertos.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/freertos.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/lwip.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/lwip.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/lwip.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/main.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/main.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/stm32f4xx_hal_msp.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/stm32f4xx_hal_msp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/stm32f4xx_hal_msp.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/stm32f4xx_it.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Src/stm32f4xx_it.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/stm32f4xx_it.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


