################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c \
C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c 

OBJS += \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dsi.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_eth.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_nor.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sdram.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sram.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_fmc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.o 

C_DEPS += \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dsi.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_eth.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_nor.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sdram.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sram.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_fmc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dac_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dsi.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dsi.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_eth.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_eth.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_ltdc_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_nor.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_nor.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sai_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sdram.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sdram.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sram.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sram.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_fmc.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_fmc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.o: C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -D__weak="__attribute__((weak))" -D__packed="__attribute__((__packed__))" -DUSE_HAL_DRIVER -DSTM32F429xx -DARM_MATH_CM4 -D__FPU_PRESENT -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Inc" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/system/arch" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/ipv4/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/lwip" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/netif" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/include/posix/sys" -I"C:/Users/scott/repos/code/openstm/batteryCharger429I/Middlewares/Third_Party/LwIP/src/netif/ppp"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


